services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_PATH= /app/data/shortener.db
    volumes:
      - data:/app/data
    command:
      - flask
      - --app
      - run
      - --host=0.0.0.0
      - --port=8080

volumes:
  data: